### ISSUE TITLE
Support 18.1.0

### ISSUE THREAD

**Issue by miuirussia** [Ultra-NX/Ultra#11]
Please, add support of 18.1.0 firmware. Atmosphere released https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.7.1

https://github.com/THZoria/NX_Firmware/releases/download/18.1.0/Firmware.18.1.0.zip

**Comment by NikN52** [comment]
A lot of people are waiting for 18.1.0 support to be added.

**Comment by redraz** [comment]
I apologize for the delay, there have been a lot of Switchcraft and Ultrahand updates recently, and yet Ultra-NX is mainly designed for comfortable overclocking, so it took time to update Tuner and test that everything is stable

**Comment by redraz** [comment]
You can download the Release Candidate of the new Ultra 2.2 [at this link](https://github.com/Ultra-NX/Ultra-Resources/releases/download/Test/Ultra.zip), I checked the operation on HOS 18.1.0 and found no problems, nor did the testers. But today another Ultrahand + Switchcraft update came out, so I decided to release an RC before the release. If all is well, the full release with changelog will be this weekend.
You can also upgrade to a new version via AIO by clicking Refresh beforehand

**Comment by danilvalov** [comment]
@redraz Sorry, but AIO shows only RC1 as available version after refresh :(
When do you plan to move Ultra 2.2 to releases without RC status?
