### ISSUE TITLE
Добавить в wiki

### ISSUE THREAD

**Issue by Packuh** [Ultra-NX/Ultra#6]
В https://github.com/Ultra-NX/Ultra/wiki
в раздел "Подготовка", добавить описание - в какой формат форматировать флешку если делаешь с нуля.

**Comment by Packuh** [comment]
пункт 4. "Подготовка"
Изменить текст на:
Включите/перезагрузите консоль удерживая кнопку громкости "–" (минус) для захода в Hekate. Для перезагрузки/выключения консоли - удерживайте кнопку выключения больше 5 секунд.

**Comment by Packuh** [comment]
Добавить пункт - перед созданием бэкапа, необходимо загрузиться обычном режиме и вставить джойконы/джойстики, для того, чтоб они прописались и в будущем не приходилось их переопределять при каждой перезагрузке приставки.

**Comment by Packuh** [comment]
Шел по вики, дошел до места "/backup/"NAND id"/sysmmc "
Но у меня не создалась эта папка.

**Comment by Packuh** [comment]
"Восстановление Сиснанда"
Пункт 7 - Проверьте работу сиснанда после восстановления.

Тема не раскрыта. Как и чем проверять?

**Comment by redraz** [comment]
По пунктам:
В установке есть про формат флешки, и там советуется Fat32 и кластер 64kb, даже совет программы и ответ, почему ExFat нельзя есть.

Чутка скорректировал "подготовку".

Про джойконы информация избыточная, это как "не совать кошку в микроволновку". 

Про /backup/"NAND id"/sysmmc, а где у тебя файлы бэкапа сиснанда лежали, при создании в актуальной хекате? BOOT1 и rawnand.bin которые.

Проверить сиснанд просто - включить консоль. Включилась - бэкап работает)
