### ISSUE TITLE
Возможно слегка устарел текст разгона

### ISSUE THREAD

**Issue by catamphetamine** [Ultra-NX/Ultra#9]
Здравствуйте. Пара комментариев по тексту в Wiki про разгон приставки для "чайников".

Скачал вчера "Ультру" после множества попыток завести какой-нибудь разгон в Чифире. 

Чифир всё время зависал и приходилось стирать то карту памяти, то память самой приставки, т.к. он всё это "корраптил" после крешей. Также удивило отсутствие хоть какой-то минимальной документации на сам Чифир и на все его "ебалы" и "ебаматики".

В "Ультре", на удивление, завёлся разгон на пресете "Red" (614 MHz GPU) и RDR не вылетел за полчаса в эмуляции режима Docked (Erista). Во время чтения документации по разгону заметил небольшую неточность в тексте:

> OV (Overvolt) - Прожорливые пресеты поднятые по вольтажам, дают максимум производительности но очень много жрут, идеальны для Дока.

Из текста не совсем понятно, какие конкретно пресеты — Red и Hell — являются "OV", потому что в интерфейсе нет пометки "OV".

> Теперь - выбираем пресет в зависимости от желаемого стиля использования консоли, ECO, Classic или OV.

Аналогично: "OV".

> Идем сверху-вниз, если выбрали ECO, то ставим пресет "Alpha - ECO+", если выбрали OV, то "Hell - OV+".

Не совсем понятно, что значит "сверху-вниз". Возможно вообще убрать эту фразу?

Также нет в интефейсе пресетов: ни "Alpha - ECO+", ни "Hell - OV+".
Есть только: Core, Mega, Ultra, Red, Hell, с пометками: LOW, MED, HIGH, ..., MAX+.

> Если никаких глюков/глитчей/зависаний/артефактов не обнаружено - поздравляем, ваша консоль выиграла в кремниевой лотерее.

Шаг последний. Но ничего не сказано про то, как завершить "полный разгон" — не сказано про разгон CPU. 
Где-то в тексте было написано, что "CPU можно гнать независимо и потом, т.к. он не связан", но конкретно в разделе "Базовый уровень" ничего не сказано, как гнать CPU "чайникам". Я лично просто поставил `1785 MHz` как offical oc max for erista в любом режиме приставки.

**Comment by catamphetamine** [comment]
Оффтопик: Создавал ещё сегодня ишью в репозитории Mission Control о том, что он "паникует" на последней версии Ultra. Автор закрыл баг, так что я хз, что там и куда и кому и зачем. Я не пользуюсь Mission Control. Просто поставил сначала, "чтобы было". https://github.com/ndeadly/MissionControl/issues/817

**Comment by redraz** [comment]
У Эрист свои пресеты и свои пометки, под описанием ECO пресетов на вики даже указано "Только для Марико (V2/Lite/Oled)."
Про цпу я не понял, есть отдельный раздел посвященный его андервольту.
Выставление частот под игры - дело персональное, под отдельные настройки и отдельные игры и отдельные консоли.

**Comment by redraz** [comment]
В Ультре используется свой Мишн Контроль собранный Pugemon под послеlнюю HOS 18, с вырезанной перекраской джойконов в украинский флаг. Если с ней какие-то проблемы - могу передать Pugemon'у

**Comment by catamphetamine** [comment]
> У Эрист свои пресеты и свои пометки, под описанием ECO пресетов на вики даже указано "Только для Марико (V2/Lite/Oled)."

Да, я прочёл это как "ECO пресет доступен только для Mariko, но все остальные пресеты идентичны".

> В Ультре используется свой Мишн Контроль собранный Pugemon под послеlнюю HOS 18, с вырезанной перекраской джойконов в украинский флаг. Если с ней какие-то проблемы - могу передать Pugemon'у

Хмм, то есть можно было не устанавливать Mission Control... Не помню, предлагал ли он заменить файлы во время копирования. На текущий момент времени в sysmodules его нет. Ну ладно, это к теме не относится.

Ладно, я тогда закрою этот issue. Спасибо.

**Comment by catamphetamine** [comment]
> Про цпу я не понял, есть отдельный раздел посвященный его андервольту.

Нет раздела "Как гнать CPU для чайников".
Есть раздел "Как гнать RAM и GPU" с подробной инструкцией про 15 мин + 2 мин * N, но дальше этот раздел "обрывается", не рассказав ничего про то, как теперь "донастроить" CPU под настроенные RAM и GPU.
"Отдельный раздел" больше подходит для "advanced" пользователей в данном случае.
